CREATE TABLE authors
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE quotes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content        VARCHAR(255),
    current_rating INTEGER,
    author_id      BIGINT                                  NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_quotes PRIMARY KEY (id)
);

CREATE TABLE ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    difference INTEGER,
    total      INTEGER,
    author_id  BIGINT                                  NOT NULL,
    date       TIMESTAMP WITHOUT TIME ZONE,
    quote_id   BIGINT                                  NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_ratings PRIMARY KEY (id)
);

ALTER TABLE authors
    ADD CONSTRAINT uc_authors_email UNIQUE (email);

ALTER TABLE authors
    ADD CONSTRAINT uc_authors_name UNIQUE (name);

ALTER TABLE quotes
    ADD CONSTRAINT FK_QUOTES_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_QUOTE FOREIGN KEY (quote_id) REFERENCES quotes (id);